### ISSUE TITLE
Built in CODE server not loading

### ISSUE THREAD

**Issue by Jolopu** [CollaboraOnline/richdocumentscode#237]
I'm on a shared host and have all the latest versions of NC and collabora installed. I'm on PHP 8.2. Since 23.5.102  all versions of collabora server are not loading. When downgrading to 23.5.5 it loads. I don't know what the issue is. Maybe it has something to do with fontconfig. Anyway I will stay on 23..5.5 until a newer version is loading again. 

I think this might affect also other users on shared hosts. If any developer is interested in researching this issue, I can provide access to my test server. Just give me an email.

Thanks!

**Comment by Jolopu** [comment]
I just updated to NC 27.1.1 an richdocumentscode 23.5.402 and the server is loading. Even if nobody commented on this issue, it seems to be resolved now. Thanks a lot!

**Comment by joshtrichards** [comment]
Hi @Jolopu - Sounds like your matter is resolved. Feel free to close your issue out!

**Comment by Jolopu** [comment]
Hi @joshtrichards - Unfortunately the matter is not resolved. I have to comment out these lines in proxy.php:
`if ($return)
 return 'no_fontconfig';
`
If I don't the server still wont load in the latest version 23.5.503.

**Comment by joshtrichards** [comment]
Duplicate of #162

**Comment by Janoo1606** [comment]
I have also a problem with the built-in code server. The documents get stuck while loading. But it affects all documents whether in the group folder or in my own directory. And also newly created ones.

Use the extensions: Nextcloud Office with Collabora Online - Built-in CODE Server. It works with the demo server setting, but not with the built-in Collabora Online Development Edition setting.

The protocol says: Failed to generate token for existing file on direct editing

Collabora Online - Built-in CODE Server: 23.5.503
Nextcloud: 27.1.3
Nextcloud Office: 8.2.2

Does somebody has any idea?

**Comment by timur-g** [comment]
Let us slose ad duplicate. Last post seems out of topic.
